export const carsData = [
  {
    carNumber: "PREM123",
    model: "Mercedes-Benz S-Class",
    photoUrl: "/images/mercedes-s-class.jpg",
    class: "Premium",
    transmission: "Automatic",
    numberOfDoors: 4,
    airConditioning: true,
    enginePower: 450,
    pricingTiers: { 3: 200, 6: 170, 10: 120 },
  },
  {
    carNumber: "LIM1",
    model: "Citroen C4 2016",
    photoUrl: "/images/Citroen_C4_2016.jpg",
    class: "Limousine",
    color: "Brown (Metallic)",
    transmission: "Automatic",
    seats: 5,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "diesel",
    enginePower: 120,
    pricingTiers: { 3: 35, 6: 30, 10: 25 },
  },
  {
    carNumber: "MBUS1",
    model: "Citroen C4 Grand Picasso 2015",
    photoUrl: "/images/Citroen_Picasso_2015.jpg",
    class: "MiniBus",
    color: "Brown (Metallic)",
    transmission: "Automatic",
    seats: 7,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "diesel",
    enginePower: 120,
    pricingTiers: { 3: 40, 6: 35, 10: 30 },
  },
  {
    carNumber: "MBUS2",
    model: "Citroen C4 Grand Picasso 2016",
    photoUrl: "/images/Citroen_Picasso_2016.jpg",
    class: "MiniBus",
    color: "Black",
    transmission: "Automatic",
    seats: 7,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "diesel",
    enginePower: 120,
    pricingTiers: { 3: 40, 6: 35, 10: 30 },
  },
  {
    carNumber: "CROSS1",
    model: "Ford EcoSport 2016",
    photoUrl: "/images/Ford_EcoSport_2016.jpg",
    class: "Crossover",
    color: "Black",
    transmission: "Manual",
    seats: 5,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "petrol",
    enginePower: 125,
    pricingTiers: { 3: 40, 6: 35, 10: 30 },
  },
  {
    carNumber: "COMP1",
    model: "Ford Fiesta 2017",
    photoUrl: "/images/Ford_Fiesta_2017.jpg",
    class: "Compact",
    color: "Black (Metallic)",
    transmission: "Automatic",
    seats: 5,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "petrol",
    enginePower: 100,
    pricingTiers: { 3: 35, 6: 30, 10: 25 },
  },
  {
    carNumber: "CROSS2",
    model: "Honda HR-V 2018",
    photoUrl: "/images/Honda_HRV_2018.jpg",
    class: "Crossover",
    color: "Blue (Metallic)",
    transmission: "Manual",
    seats: 5,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "diesel",
    enginePower: 120,
    pricingTiers: { 3: 35, 6: 30, 10: 25 },
  },
  {
    carNumber: "COMP2",
    model: "Hyundai i 10 2017",
    photoUrl: "/images/Hyundai_i10_2017.jpg",
    class: "Compact",
    color: "White",
    transmission: "Manual",
    seats: 4,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "petrol",
    enginePower: 87,
    pricingTiers: { 3: 35, 6: 30, 10: 25 },
  },
  {
    carNumber: "COMP3",
    model: "Hyundai i 10 2016",
    photoUrl: "/images/Hyundai_i10_2016.jpg",
    class: "Compact",
    color: "White",
    transmission: "Manual",
    seats: 4,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "petrol",
    enginePower: 87,
    pricingTiers: { 3: 35, 6: 30, 10: 25 },
  },
  {
    carNumber: "COMP4",
    model: "Hyundai i 10 2015",
    photoUrl: "/images/Hyundai_i10_2015.jpg",
    class: "Compact",
    color: "Grey",
    transmission: "Manual",
    seats: 4,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "petrol",
    enginePower: 87,
    pricingTiers: { 3: 35, 6: 30, 10: 25 },
  },
  {
    carNumber: "COMP5",
    model: "Hyundai i 10 2017",
    photoUrl: "/images/Hyundai_i10_2017_2.jpg",
    class: "Compact",
    color: "White",
    transmission: "Manual",
    seats: 4,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "petrol",
    enginePower: 87,
    pricingTiers: { 3: 35, 6: 30, 10: 25 },
  },
  {
    carNumber: "COMP6",
    model: "Hyundai i 10 2019",
    photoUrl: "/images/Hyundai_i10_2019.jpg",
    class: "Compact",
    color: "Red",
    transmission: "Manual",
    seats: 4,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "petrol",
    enginePower: 71,
    pricingTiers: { 3: 35, 6: 30, 10: 25 },
  },
  {
    carNumber: "LIM2",
    model: "Hyundai i 30 2021",
    photoUrl: "/images/Hyundai_i30_2021.jpg",
    class: "Limousine",
    color: "Silver",
    transmission: "Automatic",
    seats: 5,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "diesel",
    enginePower: 116,
    pricingTiers: { 3: 40, 6: 35, 10: 30 },
  },
  {
    carNumber: "LIM3",
    model: "Hyundai i 30 2021",
    photoUrl: "/images/Hyundai_i30_2021_2.jpg",
    class: "Limousine",
    color: "White (Metallic)",
    transmission: "Automatic",
    seats: 5,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "diesel",
    enginePower: 116,
    pricingTiers: { 3: 40, 6: 35, 10: 30 },
  },
  {
    carNumber: "CROSS3",
    model: "Hyundai Kona 2020",
    photoUrl: "/images/Hyundai_Kona_2020.jpg",
    class: "Crossover",
    color: "Black",
    transmission: "Manual",
    seats: 5,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "perol",
    enginePower: 120,
    pricingTiers: { 3: 40, 6: 35, 10: 30 },
  },
  {
    carNumber: "LIM4",
    model: "Mercedes-Benz CLA 180 2014",
    photoUrl: "/images/Mercedes_Benz_2014.jpg",
    class: "Limousine",
    color: "Black (Metallic)",
    transmission: "Manual",
    seats: 5,
    numberOfDoors: 4,
    airConditioning: true,
    fueltype: "petrol",
    enginePower: 125,
    pricingTiers: { 3: 40, 6: 35, 10: 30 },
  },
  {
    carNumber: "COMP7",
    model: "Nissan Note 2014",
    photoUrl: "/images/Nissan_Note_2014.jpg",
    class: "Compact",
    color: "White (Metallic)",
    transmission: "Manual",
    seats: 4,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "diesel",
    enginePower: 90,
    pricingTiers: { 3: 40, 6: 35, 10: 30 },
  },
  {
    carNumber: "MBUS3",
    model: "Nissan NV 200 2017",
    photoUrl: "/images/Nissan_NV200_2017.jpg",
    class: "MiniBus",
    color: "Black (Metallic)",
    transmission: "Manual",
    seats: 7,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "diesel",
    enginePower: 110,
    pricingTiers: { 3: 40, 6: 35, 10: 30 },
  },
  {
    carNumber: "COMP8",
    model: "Opel Karl 2016",
    photoUrl: "/images/Opel_Karl_2016.jpg",
    class: "Compact",
    color: "White",
    transmission: "Manual",
    seats: 5,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "petrol",
    enginePower: 75,
    pricingTiers: { 3: 35, 6: 30, 10: 25 },
  },
  {
    carNumber: "COMP9",
    model: "Opel Karl 2015",
    photoUrl: "/images/Opel_Karl_2015.jpg",
    class: "Compact",
    color: "Blue (Metallic)",
    transmission: "Manual",
    seats: 5,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "petrol",
    enginePower: 75,
    pricingTiers: { 3: 35, 6: 30, 10: 25 },
  },
  {
    carNumber: "CONV1",
    model: "Renault Twingo 2017",
    photoUrl: "/images/Renault_Twingo_2017.jpg",
    class: "Convertible",
    color: "Dark blue",
    transmission: "Automatic",
    seats: 5,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "petrol",
    enginePower: 90,
    pricingTiers: { 3: 35, 6: 30, 10: 25 },
  },
  {
    carNumber: "CROSS4",
    model: "Seat Arona 2020",
    photoUrl: "/images/Seat_Arona_2020.jpg",
    class: "Crossover",
    color: "Dark red",
    transmission: "Manual",
    seats: 5,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "natural gas(cng)",
    enginePower: 90,
    pricingTiers: { 3: 35, 6: 30, 10: 25 },
  },
  {
    carNumber: "LIM5",
    model: "Seat Leon 2019",
    photoUrl: "/images/Seat_Leon_2019.jpg",
    class: "Limousine",
    color: "White",
    transmission: "Manual",
    seats: 5,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "natural gas(cng)",
    enginePower: 130,
    pricingTiers: { 3: 35, 6: 30, 10: 25 },
  },
  {
    carNumber: "LIM6",
    model: "Subaru Trezia 2012",
    photoUrl: "/images/Subaru_Trezia_2012.jpg",
    class: "Limousine",
    color: "Silver (Metallic)",
    transmission: "Automatic",
    seats: 5,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "diesel",
    enginePower: 90,
    pricingTiers: { 3: 40, 6: 35, 10: 30 },
  },
  {
    carNumber: "COMP10",
    model: "Toyota Auris 2016",
    photoUrl: "/images/Toyota_Auris_2016.jpg",
    class: "Compact",
    color: "Light blue",
    transmission: "Manual",
    seats: 5,
    numberOfDoors: 5,
    airConditioning: true,
    fueltype: "petrol",
    enginePower: 116,
    pricingTiers: { 3: 40, 6: 35, 10: 30 },
  },
];

// export const carsData = [
//   {
//     carNumber: "PREM123",
//     model: "Mercedes-Benz S-Class",
//     photoUrl: "/images/mercedes-s-class.jpg",
//     class: "Premium",
//     transmission: "Automatic",
//     numberOfDoors: 4,
//     airConditioning: true,
//     enginePower: 450,
//     pricingTiers: { 3: 200, 6: 170, 10: 120 },
//   },
//   {
//     carNumber: "ECO456",
//     model: "Toyota Corolla",
//     photoUrl: "/images/toyota-corolla.jpg",
//     class: "Economy",
//     transmission: "Manual",
//     numberOfDoors: 4,
//     airConditioning: true,
//     enginePower: 130,
//     pricingTiers: { 3: 50, 6: 40, 10: 35 },
//     // orders: [
//     //   {
//     //     customerName: "Bob Johnson",
//     //     email: "john@john.com",
//     //     phone: "123456789",
//     //     rentalStartDate: new Date("2024-09-20"),
//     //     rentalEndDate: new Date("2024-09-25"),
//     //     totalPrice: 250, // 5 days * 50 per day
//     //   },
//     //   {
//     //     customerName: "Alice Brown",
//     //     email: "john@john.com",
//     //     phone: "123456789",
//     //     rentalStartDate: new Date("2024-10-05"),
//     //     rentalEndDate: new Date("2024-10-07"),
//     //     totalPrice: 100, // 2 days * 50 per day
//     //   },
//     // ],
//   },
//   {
//     carNumber: "MIN789",
//     model: "Ford Transit",
//     photoUrl: "/images/ford-transit.jpg",
//     class: "MiniBus",
//     transmission: "Automatic",
//     numberOfDoors: 5,
//     airConditioning: true,
//     enginePower: 200,
//     pricingTiers: { 3: 120, 6: 100, 10: 95 },
//     // orders: [
//     //   {
//     //     customerName: "Charlie Wilson",
//     //     email: "john@john.com",
//     //     phone: "123456789",
//     //     rentalStartDate: new Date("2024-09-15"),
//     //     rentalEndDate: new Date("2024-09-18"),
//     //     totalPrice: 360, // 3 days * 120 per day
//     //   },
//     //   {
//     //     customerName: "Diana Lee",
//     //     email: "john@john.com",
//     //     phone: "123456789",
//     //     rentalStartDate: new Date("2024-10-10"),
//     //     rentalEndDate: new Date("2024-10-14"),
//     //     totalPrice: 480, // 4 days * 120 per day
//     //   },
//     // ],
//   },
// ];
